In [153]:
import tensorflow as tf
import os
from PIL import Image

In [39]:
n_epochs = 2
batch_size = 3
buffer_size = 24

In [40]:
ds = tf.data.Dataset.range(12)

In [41]:
ds = ds.shuffle(buffer_size=buffer_size, reshuffle_each_iteration=True)

In [42]:
ds = ds.batch(batch_size)

In [43]:
ds = ds.repeat(n_epochs)

In [44]:
it = ds.make_one_shot_iterator()

In [45]:
next_batch = it.get_next()

In [46]:
sess = tf.Session()
print("epoch 1")
for _ in range(4):
    print(sess.run(next_batch))
    
print("epoch 2")
for _ in range(4):
    print(sess.run(next_batch))

epoch 1
[8 6 1]
[9 4 3]
[2 7 5]
[ 0 11 10]
epoch 2
[11  7  4]
[2 8 3]
[10  0  1]
[9 6 5]


In [129]:
path = '../data/train'
train_ids = ['../data/train/images/'+f for f in next(os.walk(path + "/images"))[2]]
train_imgs = tf.constant(train_ids)
train_masks = tf.constant(train_ids)

In [130]:
train_ids[:5]

['../data/train/images/46bbe12b2c.png',
 '../data/train/images/1d2382ac3f.png',
 '../data/train/images/a37249665e.png',
 '../data/train/images/4b3502ca99.png',
 '../data/train/images/dcbb6474ee.png']

In [131]:
train_set = tf.data.Dataset.from_tensor_slices(train_imgs)
train_set = train_set.shuffle(buffer_size=len(train_ids)*2)
# train_set = train_set.batch(5)

In [55]:
it = train_set.make_one_shot_iterator()
next_batch = it.get_next()

In [62]:
sess = tf.Session()
print("epoch 1")
for _ in range(2):
    print(sess.run(next_batch))

epoch 1
(array([b'68d9f77646.png', b'2ecb2b0797.png', b'9bf982cf65.png',
       b'c59e5f46c0.png', b'12a953a079.png'], dtype=object), array([b'68d9f77646.png', b'2ecb2b0797.png', b'9bf982cf65.png',
       b'c59e5f46c0.png', b'12a953a079.png'], dtype=object))
(array([b'3b5e9c6e05.png', b'675cab373f.png', b'937ea43a65.png',
       b'3ca252f526.png', b'85e6b4cb1c.png'], dtype=object), array([b'3b5e9c6e05.png', b'675cab373f.png', b'937ea43a65.png',
       b'3ca252f526.png', b'85e6b4cb1c.png'], dtype=object))


In [145]:
def _parse_function(filename):
    image_string = tf.read_file(filename)
    image_decoded = tf.image.decode_jpeg(image_string)
    image_resized = tf.image.resize_images(image_decoded, [101, 101])

    return image_string

In [150]:
train_set = tf.data.Dataset.from_tensor_slices(train_imgs)
train_set = train_set.shuffle(buffer_size=len(train_ids)*2)
train_set = train_set.map(_parse_function)
train_set = train_set.batch(5)


In [151]:
it = train_set.make_one_shot_iterator()
next_batch = it.get_next()

In [154]:
sess = tf.Session()
print("epoch 1")
for _ in range(2):
    imgs = sess.run(next_batch)
    for i, img in enumerate(imgs):
        im = Image.fromarray(img, "RGB")
        im.save(str(i)+".jpeg")

epoch 1


AttributeError: 'bytes' object has no attribute '__array_interface__'

In [105]:
os.path.isfile('../data/train/images/97515a958d.png')

True